---
- name: test_role
  hosts: sql
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - {
        role: mysql,
        version: 5.5,
        root_password: 'mysuperpassword',
        mysql_databases: [{ name: 'mydb1' }, { name: 'mydb2' }],
      }
